# Generated by Django 5.1.15 on 2026-02-09 03:36

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('max_adults', models.PositiveSmallIntegerField(default=2, verbose_name='Máx. Adultos')),
                ('max_children', models.PositiveSmallIntegerField(default=1, verbose_name='Máx. Crianças')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diária Base')),
            ],
            options={
                'verbose_name': 'Categoria de Quarto',
                'verbose_name_plural': 'Categorias de Quartos',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Número do Quarto')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Andar')),
                ('status', django_fsm.FSMField(choices=[('AVAILABLE', 'Disponível (Limpo)'), ('OCCUPIED', 'Ocupado'), ('DIRTY', 'Sujo (Aguardando Limpeza)'), ('MAINTENANCE', 'Em Manutenção')], default='AVAILABLE', max_length=50, protected=True, verbose_name='Status Atual')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='accommodations.roomcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['number'],
            },
        ),
    ]
