# Generated by Django 5.1.15 on 2026-02-09 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('passport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Passaporte')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'ordering': ['name'],
            },
        ),
    ]
