# Generated by Django 5.1.15 on 2026-02-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='document',
            field=models.CharField(blank=True, max_length=20, verbose_name='Documento (CPF/Passaporte)'),
        ),
    ]
