# Generated by Django 6.0.2 on 2026-02-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome Completo'),
        ),
    ]
