# Generated by Django 5.1.15 on 2026-02-10 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Receita (Pagamento)'), ('EXPENSE', 'Despesa (Saída)'), ('REFUND', 'Estorno'), ('CONSUMPTION', 'Consumo (Frigobar/Bar)')], default='INCOME', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financials.product', verbose_name='Produto Consumido'),
        ),
    ]
