# Generated by Django 5.1.15 on 2026-02-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_product_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque Atual'),
        ),
    ]
