# Generated by Django 6.0.2 on 2026-02-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_roomallocation_options_alter_booking_status_and_more'),
        ('financials', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregistersession',
            name='calculated_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Calculado'),
        ),
        migrations.AlterField(
            model_name='cashregistersession',
            name='closing_notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cashregistersession',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferença'),
        ),
        migrations.AlterField(
            model_name='cashregistersession',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financials.paymentmethod', verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financials.cashregistersession', verbose_name='Sessão do Caixa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Receita (Entrada)'), ('EXPENSE', 'Despesa (Saída)'), ('REFUND', 'Estorno'), ('CONSUMPTION', 'Consumo (Frigobar/Bar)')], default='INCOME', max_length=20),
        ),
    ]
