# Generated by Django 6.0.2 on 2026-02-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_alter_cashregistersession_calculated_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Receita (Entrada)'), ('EXPENSE', 'Despesa (Saída)'), ('REFUND', 'Estorno'), ('CONSUMPTION', 'Consumo (Frigobar/Bar)')], db_index=True, default='INCOME', max_length=20),
        ),
    ]
