# Generated by Django 5.1.15 on 2026-02-09 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmada'), ('CANCELED', 'Cancelada'), ('CHECKED_IN', 'Check-in Realizado'), ('COMPLETED', 'Finalizada')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guests.guest', verbose_name='Hóspede Principal')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Data Entrada')),
                ('end_date', models.DateField(verbose_name='Data Saída')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Diária Acordado')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accommodations.room', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Alocação de Quarto',
                'verbose_name_plural': 'Alocações de Quartos',
            },
        ),
    ]
