# Generated by Django 5.1.15 on 2026-02-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomallocation',
            options={'verbose_name': 'Quarto da Reserva', 'verbose_name_plural': 'Quartos da Reserva'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente (Aguardando Pagamento)'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'Check-in Realizado'), ('COMPLETED', 'Finalizada (Check-out)'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Status da Reserva'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Valor da Diária Acordado'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='end_date',
            field=models.DateField(verbose_name='Data de Saída (Check-out)'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accommodations.room', verbose_name='Quarto Selecionado'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='start_date',
            field=models.DateField(verbose_name='Data de Entrada (Check-in)'),
        ),
    ]
