# Generated by Django 6.0.2 on 2026-02-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_roomallocation_options_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente (Aguardando Pagamento)'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'Check-in Realizado'), ('COMPLETED', 'Finalizada (Check-out)'), ('CANCELED', 'Cancelada')], db_index=True, default='PENDING', max_length=20, verbose_name='Status da Reserva'),
        ),
    ]
